# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\pay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime,QDate, QTime, Qt, QRegExp
from PyQt5.QtGui import QRegExpValidator

# Подключение БД
import mysql.connector as mc

mydb = mc.connect(
     host="localhost",
     user="root",
     password="",
     database="club"
)
print("Успешное подключение БД - Оплата")
mycursor = mydb.cursor()

# DOCX
import docx # Подключение к docx
from docx.shared import Pt # Подключение размер шрифта


class Ui_PayWindow(object):
    
    def setupUi(self, PayWindow):
        PayWindow.setObjectName("PayWindow")
        PayWindow.resize(400, 700)
        PayWindow.setMinimumSize(QtCore.QSize(400, 700))
        PayWindow.setMaximumSize(QtCore.QSize(400, 700))
        PayWindow.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/LOGO_icon_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PayWindow.setWindowIcon(icon)
        PayWindow.setStyleSheet("background-color: #151819;")
        self.centralwidget = QtWidgets.QWidget(PayWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QFrame(self.centralwidget)
        self.title.setMaximumSize(QtCore.QSize(16777215, 100))
        self.title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title.setObjectName("title")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.title)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.title)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #fff;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.title)
        self.line.setMaximumSize(QtCore.QSize(400, 2))
        self.line.setStyleSheet("background-color: rgb(127, 127, 127);")
        self.line.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.title)
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setStyleSheet("")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info = QtWidgets.QFrame(self.frame_1)
        self.info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info.setObjectName("info")
        self.gridLayout = QtWidgets.QGridLayout(self.info)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")

##################

        self.input_email = QtWidgets.QLineEdit(self.info)
        self.input_email.textChanged.connect(self.time)

##################

        self.input_email.setMaximumSize(QtCore.QSize(325, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(18)
        self.input_email.setFont(font)
        self.input_email.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.input_email.setText("")
        self.input_email.setCursorPosition(0)
        self.input_email.setAlignment(QtCore.Qt.AlignCenter)
        self.input_email.setObjectName("input_email")
        self.gridLayout.addWidget(self.input_email, 9, 0, 1, 1)

###################

        self.input_email_2 = QtWidgets.QLineEdit(self.info)
        self.input_email_2.textChanged.connect(self.summa)

###################

        self.input_email_2.setMaximumSize(QtCore.QSize(325, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(18)
        self.input_email_2.setFont(font)
        self.input_email_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.input_email_2.setText("")
        self.input_email_2.setCursorPosition(0)
        self.input_email_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_email_2.setObjectName("input_email_2")
        self.gridLayout.addWidget(self.input_email_2, 15, 0, 1, 1)
        self.text_pass = QtWidgets.QLabel(self.info)
        self.text_pass.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(17)
        self.text_pass.setFont(font)
        self.text_pass.setStyleSheet("color: #fff;")
        self.text_pass.setObjectName("text_pass")
        self.gridLayout.addWidget(self.text_pass, 4, 0, 1, 1)

##################

        self.input_fio = QtWidgets.QLineEdit(self.info)
        self.input_fio.textChanged.connect(self.id_clients)

###################

        self.input_fio.setMaximumSize(QtCore.QSize(325, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(18)
        self.input_fio.setFont(font)
        self.input_fio.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.input_fio.setText("")
        self.input_fio.setCursorPosition(0)
        self.input_fio.setAlignment(QtCore.Qt.AlignCenter)
        self.input_fio.setObjectName("input_fio")
        self.gridLayout.addWidget(self.input_fio, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.info)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: red;")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 16, 0, 1, 1)
        self.text_login = QtWidgets.QLabel(self.info)
        self.text_login.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(17)
        self.text_login.setFont(font)
        self.text_login.setStyleSheet("color: #fff;")
        self.text_login.setObjectName("text_login")
        self.gridLayout.addWidget(self.text_login, 0, 0, 1, 1)

################

        self.input_login_2 = QtWidgets.QLineEdit(self.info)
        self.input_login_2.textChanged.connect(self.id_pc)

################

        self.input_login_2.setMaximumSize(QtCore.QSize(325, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(18)
        self.input_login_2.setFont(font)
        self.input_login_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.input_login_2.setText("")
        self.input_login_2.setCursorPosition(0)
        self.input_login_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_login_2.setObjectName("input_login_2")
        self.gridLayout.addWidget(self.input_login_2, 3, 0, 1, 1)
        self.text_phone_2 = QtWidgets.QLabel(self.info)
        self.text_phone_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(17)
        self.text_phone_2.setFont(font)
        self.text_phone_2.setStyleSheet("color: #fff;")
        self.text_phone_2.setObjectName("text_phone_2")
        self.gridLayout.addWidget(self.text_phone_2, 2, 0, 1, 1)

###############

        self.input_login = QtWidgets.QLineEdit(self.info)
        self.input_login.textChanged.connect(self.id_admin)

###############

        self.input_login.setMaximumSize(QtCore.QSize(325, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(18)
        self.input_login.setFont(font)
        self.input_login.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.input_login.setText("")
        self.input_login.setCursorPosition(0)
        self.input_login.setAlignment(QtCore.Qt.AlignCenter)
        self.input_login.setObjectName("input_login")
        self.gridLayout.addWidget(self.input_login, 5, 0, 1, 1)
        self.text_email_2 = QtWidgets.QLabel(self.info)
        self.text_email_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(17)
        self.text_email_2.setFont(font)
        self.text_email_2.setStyleSheet("color: #fff;")
        self.text_email_2.setObjectName("text_email_2")
        self.gridLayout.addWidget(self.text_email_2, 14, 0, 1, 1)
        self.text_email = QtWidgets.QLabel(self.info)
        self.text_email.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(17)
        self.text_email.setFont(font)
        self.text_email.setStyleSheet("color: #fff;")
        self.text_email.setObjectName("text_email")
        self.gridLayout.addWidget(self.text_email, 8, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.info)
        self.btn = QtWidgets.QFrame(self.frame_1)
        self.btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.btn.setSizeIncrement(QtCore.QSize(0, 1000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn.setFont(font)
        self.btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn.setObjectName("btn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btn)
        self.horizontalLayout.setObjectName("horizontalLayout")

################

        self.btn_add = QtWidgets.QPushButton(self.btn)
        self.btn_add.clicked.connect(self.insert_pay)

###############
        self.btn_add.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(15)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("QPushButton{\n"
"background-color: rgb(224, 65, 61);\n"
"color: #fff;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #690200;\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)

###########

        self.btn_cancel = QtWidgets.QPushButton(self.btn)
        self.btn_cancel.clicked.connect(PayWindow.close)

###########

        self.btn_cancel.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(15)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("QPushButton{\n"
"background-color: rgb(224, 65, 61);\n"
"color: #fff;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #690200;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout_2.addWidget(self.btn)
        self.verticalLayout.addWidget(self.frame_1)
        PayWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PayWindow)
        QtCore.QMetaObject.connectSlotsByName(PayWindow)

######################## БД ################################################

    def insert_pay(self):

        # Рандомный пароль
        import random

        password_length = 8
        charecters = "abcde12345"
        password = ""

        for index in range(password_length):
            password = password + random.choice(charecters)

        print("Пароль: {}".format(password))

        # Время
        tim = QTime.currentTime()
        tm = tim.toString()
        
        # Дата
        date = QDate.currentDate()
        dt = date.toString(Qt.ISODate)

        id_clients = self.input_fio.text()
        id_pc = self.input_login_2.text()
        id_admin = self.input_login.text()
        time = self.input_email.text()
        sum = self.input_email_2.text()

        if len(id_clients) == 0:
            self.label_2.setText("Введите ID Пользователя!")
            return
        
        if len(id_pc) == 0:
            self.label_2.setText("Введите ID ПК!")
            return
        
        if len(id_admin) == 0:
            self.label_2.setText("Введите ваш ID!")
            return
        
        if len(time) == 0:
            self.label_2.setText("Введите время использования!")
            return
        
        if len(sum) == 0:
            self.label_2.setText("Введите сумму!")
            return

        try:
            query = "INSERT INTO visit (id_clients, id_pc, id_admin, time, sum) VALUES (%s, %s, %s, %s, %s)"
            value = (id_clients, id_pc, id_admin, time, sum)
            
            mycursor.execute(query, value)
            mydb.commit()

            self.label_2.setText("Успешно оплачено")
            
############ ЧЕК ###################################################
            
            doc = docx.Document()
            style = doc.styles['Normal'] # Стили текста
            style.font.name = 'Courier New CYR' # Шрифт
            style.font.size = Pt(20) # Размер шрифта
            
            doc.add_paragraph('ООО "Cyber Club"') # ЗАГОЛОВОК

            par1 = doc.add_paragraph('')
            par2 = doc.add_paragraph('')
            par3 = doc.add_paragraph('')
            par4 = doc.add_paragraph('')
            par5 = doc.add_paragraph('')
            par6 = doc.add_paragraph('')
            par7 = doc.add_paragraph('')
            par8 = doc.add_paragraph('')
            par17 = doc.add_paragraph('')
            par9 = doc.add_paragraph('')
            par10 = doc.add_paragraph('')
            par11 = doc.add_paragraph('')
            par13 = doc.add_paragraph('')
            par14 = doc.add_paragraph('')
            par15 = doc.add_paragraph('')
            par16 = doc.add_paragraph('')


####### ЗАПОЛНЕНИЕ #################################################

            par1.add_run('Добро пожаловать')
            par2.add_run('ККМ 00000001     #0001')
            par3.add_run('ИНН 0000000000001')
            par4.add_run('      ЭКЛЗ 0000000001')
            par5.add_run(dt +" "+ tm)
            par6.add_run("ID АДМИНИСТРАТОРА - " + id_admin)
            par7.add_run("ID ПОЛЬЗОВАТЕЛЯ - " + id_clients)
            par8.add_run("№ ПК - " + id_pc).bold=True
            par17.add_run("Пароль - " + password).bold=True
            par9.add_run("АРЕНДА ПК НА " + time)
            par10.add_run('= ' + sum)
            par11.add_run('______________________')
            par13.add_run("ИТОГ          " + sum +" ₽").bold=True
            par14.add_run("НАЛИЧ/КАРТОЙ = " + sum + " ₽")
            par15.add_run('***********************')
            par16.add_run('       00000001# 000001')
 
            doc.save('chek.docx') # Сохранение/скачивание
            

        except mc.Error as e:
            self.label_2.setText("Ошибка при заполнение!")

################ Ограничитель ###################################################

# Пользователи

    def id_clients(self):

        reg_ex = QRegExp("[0-9]{3}")
        input_validator = QRegExpValidator(reg_ex, self.input_fio)
        self.input_fio.setValidator(input_validator)

# Админстраторы

    def id_admin(self):

        reg_ex = QRegExp("[0-9]{3}")
        input_validator = QRegExpValidator(reg_ex, self.input_login)
        self.input_login.setValidator(input_validator)

# ПК

    def id_pc(self):

        reg_ex = QRegExp("[0-9]{3}")
        input_validator = QRegExpValidator(reg_ex, self.input_login_2)
        self.input_login_2.setValidator(input_validator)

# Время

    def time(self):

        reg_ex = QRegExp("[0-9:]{4}")
        input_validator = QRegExpValidator(reg_ex, self.input_email)
        self.input_email.setValidator(input_validator)

# Сумма

    def summa(self):

        reg_ex = QRegExp("[0-9]{5}")
        input_validator = QRegExpValidator(reg_ex, self.input_email_2)
        self.input_email_2.setValidator(input_validator)

#####################################################################################

    def retranslateUi(self, PayWindow):
        _translate = QtCore.QCoreApplication.translate
        PayWindow.setWindowTitle(_translate("PayWindow", "Оплата"))
        self.label.setText(_translate("PayWindow", "Оплата"))
        self.input_email.setPlaceholderText(_translate("PayWindow", "1:11"))
        self.input_email_2.setPlaceholderText(_translate("PayWindow", "1000"))
        self.text_pass.setText(_translate("PayWindow", "ID Администратора"))
        self.input_fio.setPlaceholderText(_translate("PayWindow", "ID"))
        self.text_login.setText(_translate("PayWindow", "ID Пользователя"))
        self.input_login_2.setPlaceholderText(_translate("PayWindow", "ID"))
        self.text_phone_2.setText(_translate("PayWindow", "ID ПК"))
        self.input_login.setPlaceholderText(_translate("PayWindow", "ID"))
        self.text_email_2.setText(_translate("PayWindow", "Сумма"))
        self.text_email.setText(_translate("PayWindow", "Время"))
        self.btn_add.setText(_translate("PayWindow", "Оплатить"))
        self.btn_cancel.setText(_translate("PayWindow", "Отмена"))


import icon_and_logo_py.Logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PayWindow = QtWidgets.QMainWindow()
    ui = Ui_PayWindow()
    ui.setupUi(PayWindow)
    PayWindow.show()
    sys.exit(app.exec_())
